# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cyber_header_pb2 as cyber__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatter.proto',
  package='cybertron.proto',
  syntax='proto2',
  serialized_pb=_b('\n\rchatter.proto\x12\x0f\x63ybertron.proto\x1a\x12\x63yber_header.proto\"[\n\x07\x43hatter\x12\x32\n\x0c\x63yber_header\x18\x01 \x01(\x0b\x32\x1c.cybertron.proto.CyberHeader\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"?\n\x10\x43hatterBenchmark\x12\r\n\x05stamp\x18\x01 \x01(\x04\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t')
  ,
  dependencies=[cyber__header__pb2.DESCRIPTOR,])




_CHATTER = _descriptor.Descriptor(
  name='Chatter',
  full_name='cybertron.proto.Chatter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cyber_header', full_name='cybertron.proto.Chatter.cyber_header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='cybertron.proto.Chatter.seq', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='cybertron.proto.Chatter.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=145,
)


_CHATTERBENCHMARK = _descriptor.Descriptor(
  name='ChatterBenchmark',
  full_name='cybertron.proto.ChatterBenchmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='cybertron.proto.ChatterBenchmark.stamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='cybertron.proto.ChatterBenchmark.seq', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='cybertron.proto.ChatterBenchmark.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=210,
)

_CHATTER.fields_by_name['cyber_header'].message_type = cyber__header__pb2._CYBERHEADER
DESCRIPTOR.message_types_by_name['Chatter'] = _CHATTER
DESCRIPTOR.message_types_by_name['ChatterBenchmark'] = _CHATTERBENCHMARK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chatter = _reflection.GeneratedProtocolMessageType('Chatter', (_message.Message,), dict(
  DESCRIPTOR = _CHATTER,
  __module__ = 'chatter_pb2'
  # @@protoc_insertion_point(class_scope:cybertron.proto.Chatter)
  ))
_sym_db.RegisterMessage(Chatter)

ChatterBenchmark = _reflection.GeneratedProtocolMessageType('ChatterBenchmark', (_message.Message,), dict(
  DESCRIPTOR = _CHATTERBENCHMARK,
  __module__ = 'chatter_pb2'
  # @@protoc_insertion_point(class_scope:cybertron.proto.ChatterBenchmark)
  ))
_sym_db.RegisterMessage(ChatterBenchmark)


# @@protoc_insertion_point(module_scope)
