# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector_routing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='collector_routing.proto',
  package='adu.common.collector',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x63ollector_routing.proto\x12\x14\x61\x64u.common.collector\"\x92\x01\n\x0bRoutingInfo\x12\x14\n\x0cstart_pose_x\x18\x01 \x01(\x01\x12\x14\n\x0cstart_pose_y\x18\x02 \x01(\x01\x12\x12\n\nend_pose_x\x18\x03 \x01(\x01\x12\x12\n\nend_pose_y\x18\x04 \x01(\x01\x12\x18\n\x10routing_distance\x18\x05 \x01(\x01\x12\x15\n\rtimestamp_sec\x18\x06 \x01(\x01')
)




_ROUTINGINFO = _descriptor.Descriptor(
  name='RoutingInfo',
  full_name='adu.common.collector.RoutingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_pose_x', full_name='adu.common.collector.RoutingInfo.start_pose_x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_pose_y', full_name='adu.common.collector.RoutingInfo.start_pose_y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_pose_x', full_name='adu.common.collector.RoutingInfo.end_pose_x', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_pose_y', full_name='adu.common.collector.RoutingInfo.end_pose_y', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='routing_distance', full_name='adu.common.collector.RoutingInfo.routing_distance', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_sec', full_name='adu.common.collector.RoutingInfo.timestamp_sec', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['RoutingInfo'] = _ROUTINGINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoutingInfo = _reflection.GeneratedProtocolMessageType('RoutingInfo', (_message.Message,), dict(
  DESCRIPTOR = _ROUTINGINFO,
  __module__ = 'collector_routing_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.collector.RoutingInfo)
  ))
_sym_db.RegisterMessage(RoutingInfo)


# @@protoc_insertion_point(module_scope)
