# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decision_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import decision_pb2 as decision__pb2
import rpc_interface_pb2 as rpc__interface__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='decision_service.proto',
  package='adu.common.decision',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x64\x65\x63ision_service.proto\x12\x13\x61\x64u.common.decision\x1a\x0e\x64\x65\x63ision.proto\x1a\x13rpc_interface.proto2T\n\x03RPC\x12M\n\x0bRunDecision\x12\x17.adu.common.rpc.Request\x1a#.adu.common.decision.DecisionResult\"\x00')
  ,
  dependencies=[decision__pb2.DESCRIPTOR,rpc__interface__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RPC = _descriptor.ServiceDescriptor(
  name='RPC',
  full_name='adu.common.decision.RPC',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=84,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunDecision',
    full_name='adu.common.decision.RPC.RunDecision',
    index=0,
    containing_service=None,
    input_type=rpc__interface__pb2._REQUEST,
    output_type=decision__pb2._DECISIONRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPC)

DESCRIPTOR.services_by_name['RPC'] = _RPC

# @@protoc_insertion_point(module_scope)
