# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hmi_launch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import hmi_error_code_pb2 as hmi__error__code__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hmi_launch.proto',
  package='adu.hmi',
  syntax='proto2',
  serialized_pb=_b('\n\x10hmi_launch.proto\x12\x07\x61\x64u.hmi\x1a\x14hmi_error_code.proto\"\x1f\n\rLaunchRequest\x12\x0e\n\x06header\x18\x01 \x01(\x01\"@\n\x0eLaunchResponse\x12 \n\x04\x63ode\x18\x01 \x02(\x0e\x32\x12.adu.hmi.ErrorCode\x12\x0c\n\x04info\x18\x02 \x01(\t\"\"\n\x10\x44isengageRequest\x12\x0e\n\x06header\x18\x01 \x01(\x01\"C\n\x11\x44isengageResponse\x12 \n\x04\x63ode\x18\x01 \x02(\x0e\x32\x12.adu.hmi.ErrorCode\x12\x0c\n\x04info\x18\x02 \x01(\tB\x02P\x01')
  ,
  dependencies=[hmi__error__code__pb2.DESCRIPTOR,])




_LAUNCHREQUEST = _descriptor.Descriptor(
  name='LaunchRequest',
  full_name='adu.hmi.LaunchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.hmi.LaunchRequest.header', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=82,
)


_LAUNCHRESPONSE = _descriptor.Descriptor(
  name='LaunchResponse',
  full_name='adu.hmi.LaunchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='adu.hmi.LaunchResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='adu.hmi.LaunchResponse.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=148,
)


_DISENGAGEREQUEST = _descriptor.Descriptor(
  name='DisengageRequest',
  full_name='adu.hmi.DisengageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.hmi.DisengageRequest.header', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=184,
)


_DISENGAGERESPONSE = _descriptor.Descriptor(
  name='DisengageResponse',
  full_name='adu.hmi.DisengageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='adu.hmi.DisengageResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='adu.hmi.DisengageResponse.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=253,
)

_LAUNCHRESPONSE.fields_by_name['code'].enum_type = hmi__error__code__pb2._ERRORCODE
_DISENGAGERESPONSE.fields_by_name['code'].enum_type = hmi__error__code__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['LaunchRequest'] = _LAUNCHREQUEST
DESCRIPTOR.message_types_by_name['LaunchResponse'] = _LAUNCHRESPONSE
DESCRIPTOR.message_types_by_name['DisengageRequest'] = _DISENGAGEREQUEST
DESCRIPTOR.message_types_by_name['DisengageResponse'] = _DISENGAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaunchRequest = _reflection.GeneratedProtocolMessageType('LaunchRequest', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHREQUEST,
  __module__ = 'hmi_launch_pb2'
  # @@protoc_insertion_point(class_scope:adu.hmi.LaunchRequest)
  ))
_sym_db.RegisterMessage(LaunchRequest)

LaunchResponse = _reflection.GeneratedProtocolMessageType('LaunchResponse', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCHRESPONSE,
  __module__ = 'hmi_launch_pb2'
  # @@protoc_insertion_point(class_scope:adu.hmi.LaunchResponse)
  ))
_sym_db.RegisterMessage(LaunchResponse)

DisengageRequest = _reflection.GeneratedProtocolMessageType('DisengageRequest', (_message.Message,), dict(
  DESCRIPTOR = _DISENGAGEREQUEST,
  __module__ = 'hmi_launch_pb2'
  # @@protoc_insertion_point(class_scope:adu.hmi.DisengageRequest)
  ))
_sym_db.RegisterMessage(DisengageRequest)

DisengageResponse = _reflection.GeneratedProtocolMessageType('DisengageResponse', (_message.Message,), dict(
  DESCRIPTOR = _DISENGAGERESPONSE,
  __module__ = 'hmi_launch_pb2'
  # @@protoc_insertion_point(class_scope:adu.hmi.DisengageResponse)
  ))
_sym_db.RegisterMessage(DisengageResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('P\001'))
# @@protoc_insertion_point(module_scope)
