# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hmi_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import hmi_error_code_pb2 as hmi__error__code__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hmi_common.proto',
  package='adu.hmi',
  syntax='proto2',
  serialized_pb=_b('\n\x10hmi_common.proto\x12\x07\x61\x64u.hmi\x1a\x14hmi_error_code.proto\"2\n\x0cPolygonPoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0c\n\x01z\x18\x03 \x01(\x01:\x01\x30\"@\n\x0eStatusResponse\x12 \n\x04\x63ode\x18\x01 \x02(\x0e\x32\x12.adu.hmi.ErrorCode\x12\x0c\n\x04info\x18\x02 \x01(\tB\x02P\x01')
  ,
  dependencies=[hmi__error__code__pb2.DESCRIPTOR,])




_POLYGONPOINT = _descriptor.Descriptor(
  name='PolygonPoint',
  full_name='adu.hmi.PolygonPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='adu.hmi.PolygonPoint.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='adu.hmi.PolygonPoint.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='adu.hmi.PolygonPoint.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=101,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='adu.hmi.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='adu.hmi.StatusResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='adu.hmi.StatusResponse.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=167,
)

_STATUSRESPONSE.fields_by_name['code'].enum_type = hmi__error__code__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['PolygonPoint'] = _POLYGONPOINT
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PolygonPoint = _reflection.GeneratedProtocolMessageType('PolygonPoint', (_message.Message,), dict(
  DESCRIPTOR = _POLYGONPOINT,
  __module__ = 'hmi_common_pb2'
  # @@protoc_insertion_point(class_scope:adu.hmi.PolygonPoint)
  ))
_sym_db.RegisterMessage(PolygonPoint)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSRESPONSE,
  __module__ = 'hmi_common_pb2'
  # @@protoc_insertion_point(class_scope:adu.hmi.StatusResponse)
  ))
_sym_db.RegisterMessage(StatusResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('P\001'))
# @@protoc_insertion_point(module_scope)
