# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: localization_lidar_analysis_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import common_geometry_pb2 as common__geometry__pb2
import localization_pose_pb2 as localization__pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='localization_lidar_analysis_data.proto',
  package='adu.common.localization',
  syntax='proto2',
  serialized_pb=_b('\n&localization_lidar_analysis_data.proto\x12\x17\x61\x64u.common.localization\x1a\x0cheader.proto\x1a\x15\x63ommon_geometry.proto\x1a\x17localization_pose.proto\"C\n\x15HistogramFilterValues\x12\x0c\n\x04rows\x18\x01 \x02(\r\x12\x0c\n\x04\x63ols\x18\x02 \x02(\r\x12\x0e\n\x06values\x18\x03 \x03(\x02\"\xd4\x02\n\x16LocalLidarAnalysisData\x12\x11\n\ttimestamp\x18\x01 \x02(\x01\x12\x31\n\ninput_pose\x18\x02 \x01(\x0b\x32\x1d.adu.common.localization.Pose\x12\x45\n\rfilter_values\x18\x03 \x01(\x0b\x32..adu.common.localization.HistogramFilterValues\x12\x39\n\x0buncertainty\x18\x04 \x01(\x0b\x32$.adu.common.localization.Uncertainty\x12\x0e\n\x06others\x18\x05 \x01(\x0c\x12\x1a\n\x12localization_score\x18\x06 \x01(\x01\x12\x13\n\x0bvalid_ratio\x18\x07 \x01(\x01\x12\x18\n\x10intensity_weight\x18\x08 \x01(\x01\x12\x17\n\x0f\x61ltitude_weight\x18\t \x01(\x01')
  ,
  dependencies=[header__pb2.DESCRIPTOR,common__geometry__pb2.DESCRIPTOR,localization__pose__pb2.DESCRIPTOR,])




_HISTOGRAMFILTERVALUES = _descriptor.Descriptor(
  name='HistogramFilterValues',
  full_name='adu.common.localization.HistogramFilterValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='adu.common.localization.HistogramFilterValues.rows', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cols', full_name='adu.common.localization.HistogramFilterValues.cols', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='adu.common.localization.HistogramFilterValues.values', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=196,
)


_LOCALLIDARANALYSISDATA = _descriptor.Descriptor(
  name='LocalLidarAnalysisData',
  full_name='adu.common.localization.LocalLidarAnalysisData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='adu.common.localization.LocalLidarAnalysisData.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_pose', full_name='adu.common.localization.LocalLidarAnalysisData.input_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_values', full_name='adu.common.localization.LocalLidarAnalysisData.filter_values', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uncertainty', full_name='adu.common.localization.LocalLidarAnalysisData.uncertainty', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='others', full_name='adu.common.localization.LocalLidarAnalysisData.others', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localization_score', full_name='adu.common.localization.LocalLidarAnalysisData.localization_score', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_ratio', full_name='adu.common.localization.LocalLidarAnalysisData.valid_ratio', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensity_weight', full_name='adu.common.localization.LocalLidarAnalysisData.intensity_weight', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude_weight', full_name='adu.common.localization.LocalLidarAnalysisData.altitude_weight', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=539,
)

_LOCALLIDARANALYSISDATA.fields_by_name['input_pose'].message_type = localization__pose__pb2._POSE
_LOCALLIDARANALYSISDATA.fields_by_name['filter_values'].message_type = _HISTOGRAMFILTERVALUES
_LOCALLIDARANALYSISDATA.fields_by_name['uncertainty'].message_type = localization__pose__pb2._UNCERTAINTY
DESCRIPTOR.message_types_by_name['HistogramFilterValues'] = _HISTOGRAMFILTERVALUES
DESCRIPTOR.message_types_by_name['LocalLidarAnalysisData'] = _LOCALLIDARANALYSISDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HistogramFilterValues = _reflection.GeneratedProtocolMessageType('HistogramFilterValues', (_message.Message,), dict(
  DESCRIPTOR = _HISTOGRAMFILTERVALUES,
  __module__ = 'localization_lidar_analysis_data_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.localization.HistogramFilterValues)
  ))
_sym_db.RegisterMessage(HistogramFilterValues)

LocalLidarAnalysisData = _reflection.GeneratedProtocolMessageType('LocalLidarAnalysisData', (_message.Message,), dict(
  DESCRIPTOR = _LOCALLIDARANALYSISDATA,
  __module__ = 'localization_lidar_analysis_data_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.localization.LocalLidarAnalysisData)
  ))
_sym_db.RegisterMessage(LocalLidarAnalysisData)


# @@protoc_insertion_point(module_scope)
