# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: localization_integ_sins_pva.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import common_geometry_pb2 as common__geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='localization_integ_sins_pva.proto',
  package='adu.common.integ_sins_pva',
  syntax='proto2',
  serialized_pb=_b('\n!localization_integ_sins_pva.proto\x12\x19\x61\x64u.common.integ_sins_pva\x1a\x0cheader.proto\x1a\x15\x63ommon_geometry.proto\"\xe2\x01\n\x0cIntegSinsPva\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.adu.common.header.Header\x12&\n\x08position\x18\x02 \x01(\x0b\x32\x14.adu.common.PointLLH\x12%\n\x08velocity\x18\x03 \x01(\x0b\x32\x13.adu.common.Point3D\x12%\n\x08\x61ttitude\x18\x04 \x01(\x0b\x32\x13.adu.common.Point3D\x12\x15\n\tpva_covar\x18\x05 \x03(\x01\x42\x02\x10\x01\x12\x1a\n\x12init_and_alignment\x18\x06 \x01(\x08')
  ,
  dependencies=[header__pb2.DESCRIPTOR,common__geometry__pb2.DESCRIPTOR,])




_INTEGSINSPVA = _descriptor.Descriptor(
  name='IntegSinsPva',
  full_name='adu.common.integ_sins_pva.IntegSinsPva',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.common.integ_sins_pva.IntegSinsPva.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='adu.common.integ_sins_pva.IntegSinsPva.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='adu.common.integ_sins_pva.IntegSinsPva.velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attitude', full_name='adu.common.integ_sins_pva.IntegSinsPva.attitude', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pva_covar', full_name='adu.common.integ_sins_pva.IntegSinsPva.pva_covar', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='init_and_alignment', full_name='adu.common.integ_sins_pva.IntegSinsPva.init_and_alignment', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=328,
)

_INTEGSINSPVA.fields_by_name['header'].message_type = header__pb2._HEADER
_INTEGSINSPVA.fields_by_name['position'].message_type = common__geometry__pb2._POINTLLH
_INTEGSINSPVA.fields_by_name['velocity'].message_type = common__geometry__pb2._POINT3D
_INTEGSINSPVA.fields_by_name['attitude'].message_type = common__geometry__pb2._POINT3D
DESCRIPTOR.message_types_by_name['IntegSinsPva'] = _INTEGSINSPVA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntegSinsPva = _reflection.GeneratedProtocolMessageType('IntegSinsPva', (_message.Message,), dict(
  DESCRIPTOR = _INTEGSINSPVA,
  __module__ = 'localization_integ_sins_pva_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.integ_sins_pva.IntegSinsPva)
  ))
_sym_db.RegisterMessage(IntegSinsPva)


_INTEGSINSPVA.fields_by_name['pva_covar'].has_options = True
_INTEGSINSPVA.fields_by_name['pva_covar']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
