# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_interface_ex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import map_pb2 as map__pb2
import map_geometry_pb2 as map__geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_interface_ex.proto',
  package='adu.hdmap.common',
  syntax='proto2',
  serialized_pb=_b('\n\x16map_interface_ex.proto\x12\x10\x61\x64u.hdmap.common\x1a\tmap.proto\x1a\x12map_geometry.proto\"}\n\x15GetMapByRegionRequest\x12/\n\x0eleft_top_point\x18\x01 \x01(\x0b\x32\x17.adu.common.hdmap.Point\x12\x33\n\x12right_bottom_point\x18\x02 \x01(\x0b\x32\x17.adu.common.hdmap.Point\"\xb8\x01\n\x16GetMapByRegionResponse\x12\x44\n\nerror_code\x18\x01 \x01(\x0e\x32\x30.adu.hdmap.common.GetMapByRegionResponse.ErrCode\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\"\n\x03map\x18\x03 \x01(\x0b\x32\x15.adu.common.hdmap.Map\"!\n\x07\x45rrCode\x12\x0b\n\x07SUCCESS\x10\x01\x12\t\n\x05\x45RROR\x10\x02')
  ,
  dependencies=[map__pb2.DESCRIPTOR,map__geometry__pb2.DESCRIPTOR,])



_GETMAPBYREGIONRESPONSE_ERRCODE = _descriptor.EnumDescriptor(
  name='ErrCode',
  full_name='adu.hdmap.common.GetMapByRegionResponse.ErrCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=354,
  serialized_end=387,
)
_sym_db.RegisterEnumDescriptor(_GETMAPBYREGIONRESPONSE_ERRCODE)


_GETMAPBYREGIONREQUEST = _descriptor.Descriptor(
  name='GetMapByRegionRequest',
  full_name='adu.hdmap.common.GetMapByRegionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_top_point', full_name='adu.hdmap.common.GetMapByRegionRequest.left_top_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right_bottom_point', full_name='adu.hdmap.common.GetMapByRegionRequest.right_bottom_point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=200,
)


_GETMAPBYREGIONRESPONSE = _descriptor.Descriptor(
  name='GetMapByRegionResponse',
  full_name='adu.hdmap.common.GetMapByRegionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='adu.hdmap.common.GetMapByRegionResponse.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='adu.hdmap.common.GetMapByRegionResponse.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map', full_name='adu.hdmap.common.GetMapByRegionResponse.map', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETMAPBYREGIONRESPONSE_ERRCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=387,
)

_GETMAPBYREGIONREQUEST.fields_by_name['left_top_point'].message_type = map__geometry__pb2._POINT
_GETMAPBYREGIONREQUEST.fields_by_name['right_bottom_point'].message_type = map__geometry__pb2._POINT
_GETMAPBYREGIONRESPONSE.fields_by_name['error_code'].enum_type = _GETMAPBYREGIONRESPONSE_ERRCODE
_GETMAPBYREGIONRESPONSE.fields_by_name['map'].message_type = map__pb2._MAP
_GETMAPBYREGIONRESPONSE_ERRCODE.containing_type = _GETMAPBYREGIONRESPONSE
DESCRIPTOR.message_types_by_name['GetMapByRegionRequest'] = _GETMAPBYREGIONREQUEST
DESCRIPTOR.message_types_by_name['GetMapByRegionResponse'] = _GETMAPBYREGIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMapByRegionRequest = _reflection.GeneratedProtocolMessageType('GetMapByRegionRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMAPBYREGIONREQUEST,
  __module__ = 'map_interface_ex_pb2'
  # @@protoc_insertion_point(class_scope:adu.hdmap.common.GetMapByRegionRequest)
  ))
_sym_db.RegisterMessage(GetMapByRegionRequest)

GetMapByRegionResponse = _reflection.GeneratedProtocolMessageType('GetMapByRegionResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETMAPBYREGIONRESPONSE,
  __module__ = 'map_interface_ex_pb2'
  # @@protoc_insertion_point(class_scope:adu.hdmap.common.GetMapByRegionResponse)
  ))
_sym_db.RegisterMessage(GetMapByRegionResponse)


# @@protoc_insertion_point(module_scope)
