# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_id.proto',
  package='adu.common.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n\x0cmap_id.proto\x12\x10\x61\x64u.common.hdmap\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\x0c')
)




_ID = _descriptor.Descriptor(
  name='Id',
  full_name='adu.common.hdmap.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='adu.common.hdmap.Id.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['Id'] = _ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'map_id_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.hdmap.Id)
  ))
_sym_db.RegisterMessage(Id)


# @@protoc_insertion_point(module_scope)
