# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_parking_space.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import map_geometry_pb2 as map__geometry__pb2
import map_id_pb2 as map__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_parking_space.proto',
  package='adu.common.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n\x17map_parking_space.proto\x12\x10\x61\x64u.common.hdmap\x1a\x12map_geometry.proto\x1a\x0cmap_id.proto\"\x97\x01\n\x0cParkingSpace\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.adu.common.hdmap.Id\x12*\n\x07polygon\x18\x02 \x01(\x0b\x32\x19.adu.common.hdmap.Polygon\x12(\n\noverlap_id\x18\x04 \x03(\x0b\x32\x14.adu.common.hdmap.Id\x12\x0f\n\x07heading\x18\x05 \x01(\x01')
  ,
  dependencies=[map__geometry__pb2.DESCRIPTOR,map__id__pb2.DESCRIPTOR,])




_PARKINGSPACE = _descriptor.Descriptor(
  name='ParkingSpace',
  full_name='adu.common.hdmap.ParkingSpace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='adu.common.hdmap.ParkingSpace.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='adu.common.hdmap.ParkingSpace.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overlap_id', full_name='adu.common.hdmap.ParkingSpace.overlap_id', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='adu.common.hdmap.ParkingSpace.heading', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=231,
)

_PARKINGSPACE.fields_by_name['id'].message_type = map__id__pb2._ID
_PARKINGSPACE.fields_by_name['polygon'].message_type = map__geometry__pb2._POLYGON
_PARKINGSPACE.fields_by_name['overlap_id'].message_type = map__id__pb2._ID
DESCRIPTOR.message_types_by_name['ParkingSpace'] = _PARKINGSPACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParkingSpace = _reflection.GeneratedProtocolMessageType('ParkingSpace', (_message.Message,), dict(
  DESCRIPTOR = _PARKINGSPACE,
  __module__ = 'map_parking_space_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.hdmap.ParkingSpace)
  ))
_sym_db.RegisterMessage(ParkingSpace)


# @@protoc_insertion_point(module_scope)
