# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memory_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='memory_status.proto',
  package='adu.common.monitor',
  syntax='proto2',
  serialized_pb=_b('\n\x13memory_status.proto\x12\x12\x61\x64u.common.monitor\"/\n\x0cMemoryStatus\x12\x10\n\x08mem_size\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05')
)




_MEMORYSTATUS = _descriptor.Descriptor(
  name='MemoryStatus',
  full_name='adu.common.monitor.MemoryStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mem_size', full_name='adu.common.monitor.MemoryStatus.mem_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='adu.common.monitor.MemoryStatus.level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['MemoryStatus'] = _MEMORYSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemoryStatus = _reflection.GeneratedProtocolMessageType('MemoryStatus', (_message.Message,), dict(
  DESCRIPTOR = _MEMORYSTATUS,
  __module__ = 'memory_status_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.monitor.MemoryStatus)
  ))
_sym_db.RegisterMessage(MemoryStatus)


# @@protoc_insertion_point(module_scope)
