# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: novatel_bestvel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import novatel_header_pb2 as novatel__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='novatel_bestvel.proto',
  package='adu.common.sensor',
  syntax='proto2',
  serialized_pb=_b('\n\x15novatel_bestvel.proto\x12\x11\x61\x64u.common.sensor\x1a\x0cheader.proto\x1a\x14novatel_header.proto\"\x96\x02\n\x07\x42\x65stVel\x12)\n\x06header\x18\x18 \x01(\x0b\x32\x19.adu.common.header.Header\x12\x38\n\x0enovatel_header\x18\x01 \x01(\x0b\x32 .adu.common.sensor.NovatelHeader\x12\x17\n\x0fsolution_status\x18\x02 \x01(\r\x12\x10\n\x08vel_type\x18\x03 \x01(\r\x12\x0f\n\x07latency\x18\x04 \x01(\x02\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x02\x12\x18\n\x10horizontal_speed\x18\x06 \x01(\x01\x12\x19\n\x11track_over_ground\x18\x07 \x01(\x01\x12\x16\n\x0evertical_speed\x18\x08 \x01(\x01\x12\x10\n\x08reserved\x18\t \x01(\x02')
  ,
  dependencies=[header__pb2.DESCRIPTOR,novatel__header__pb2.DESCRIPTOR,])




_BESTVEL = _descriptor.Descriptor(
  name='BestVel',
  full_name='adu.common.sensor.BestVel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.common.sensor.BestVel.header', index=0,
      number=24, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='novatel_header', full_name='adu.common.sensor.BestVel.novatel_header', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution_status', full_name='adu.common.sensor.BestVel.solution_status', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vel_type', full_name='adu.common.sensor.BestVel.vel_type', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latency', full_name='adu.common.sensor.BestVel.latency', index=4,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='adu.common.sensor.BestVel.age', index=5,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='horizontal_speed', full_name='adu.common.sensor.BestVel.horizontal_speed', index=6,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_over_ground', full_name='adu.common.sensor.BestVel.track_over_ground', index=7,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertical_speed', full_name='adu.common.sensor.BestVel.vertical_speed', index=8,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserved', full_name='adu.common.sensor.BestVel.reserved', index=9,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=359,
)

_BESTVEL.fields_by_name['header'].message_type = header__pb2._HEADER
_BESTVEL.fields_by_name['novatel_header'].message_type = novatel__header__pb2._NOVATELHEADER
DESCRIPTOR.message_types_by_name['BestVel'] = _BESTVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BestVel = _reflection.GeneratedProtocolMessageType('BestVel', (_message.Message,), dict(
  DESCRIPTOR = _BESTVEL,
  __module__ = 'novatel_bestvel_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.sensor.BestVel)
  ))
_sym_db.RegisterMessage(BestVel)


# @@protoc_insertion_point(module_scope)
