# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: novatel_heading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import novatel_header_pb2 as novatel__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='novatel_heading.proto',
  package='adu.common.sensor',
  syntax='proto2',
  serialized_pb=_b('\n\x15novatel_heading.proto\x12\x11\x61\x64u.common.sensor\x1a\x0cheader.proto\x1a\x14novatel_header.proto\"\xab\x04\n\x07Heading\x12)\n\x06header\x18\x14 \x01(\x0b\x32\x19.adu.common.header.Header\x12\x38\n\x0enovatel_header\x18\x01 \x01(\x0b\x32 .adu.common.sensor.NovatelHeader\x12\x17\n\x0fsolution_status\x18\x02 \x01(\r\x12\x15\n\rposition_type\x18\x03 \x01(\r\x12\x17\n\x0f\x62\x61seline_length\x18\x04 \x01(\x02\x12\x0f\n\x07heading\x18\x05 \x01(\x02\x12\r\n\x05pitch\x18\x06 \x01(\x02\x12\x10\n\x08reserved\x18\x07 \x01(\x02\x12\x17\n\x0fheading_std_dev\x18\x08 \x01(\x02\x12\x15\n\rpitch_std_dev\x18\t \x01(\x02\x12\x12\n\nstation_id\x18\n \x01(\x0c\x12 \n\x18satellite_tracked_number\x18\x0b \x01(\r\x12\"\n\x1asatellite_soulution_number\x18\x0c \x01(\r\x12\x1c\n\x14satellite_number_obs\x18\r \x01(\r\x12\x1e\n\x16satellite_number_multi\x18\x0e \x01(\r\x12\x17\n\x0fsolution_source\x18\x0f \x01(\r\x12 \n\x18\x65xtended_solution_status\x18\x10 \x01(\r\x12\x1f\n\x17galileo_beidou_sig_mask\x18\x11 \x01(\r\x12\x1c\n\x14gps_glonass_sig_mask\x18\x12 \x01(\r')
  ,
  dependencies=[header__pb2.DESCRIPTOR,novatel__header__pb2.DESCRIPTOR,])




_HEADING = _descriptor.Descriptor(
  name='Heading',
  full_name='adu.common.sensor.Heading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.common.sensor.Heading.header', index=0,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='novatel_header', full_name='adu.common.sensor.Heading.novatel_header', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution_status', full_name='adu.common.sensor.Heading.solution_status', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_type', full_name='adu.common.sensor.Heading.position_type', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseline_length', full_name='adu.common.sensor.Heading.baseline_length', index=4,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='adu.common.sensor.Heading.heading', index=5,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='adu.common.sensor.Heading.pitch', index=6,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserved', full_name='adu.common.sensor.Heading.reserved', index=7,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading_std_dev', full_name='adu.common.sensor.Heading.heading_std_dev', index=8,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch_std_dev', full_name='adu.common.sensor.Heading.pitch_std_dev', index=9,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='station_id', full_name='adu.common.sensor.Heading.station_id', index=10,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satellite_tracked_number', full_name='adu.common.sensor.Heading.satellite_tracked_number', index=11,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satellite_soulution_number', full_name='adu.common.sensor.Heading.satellite_soulution_number', index=12,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satellite_number_obs', full_name='adu.common.sensor.Heading.satellite_number_obs', index=13,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satellite_number_multi', full_name='adu.common.sensor.Heading.satellite_number_multi', index=14,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution_source', full_name='adu.common.sensor.Heading.solution_source', index=15,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extended_solution_status', full_name='adu.common.sensor.Heading.extended_solution_status', index=16,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='galileo_beidou_sig_mask', full_name='adu.common.sensor.Heading.galileo_beidou_sig_mask', index=17,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_glonass_sig_mask', full_name='adu.common.sensor.Heading.gps_glonass_sig_mask', index=18,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=636,
)

_HEADING.fields_by_name['header'].message_type = header__pb2._HEADER
_HEADING.fields_by_name['novatel_header'].message_type = novatel__header__pb2._NOVATELHEADER
DESCRIPTOR.message_types_by_name['Heading'] = _HEADING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Heading = _reflection.GeneratedProtocolMessageType('Heading', (_message.Message,), dict(
  DESCRIPTOR = _HEADING,
  __module__ = 'novatel_heading_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.sensor.Heading)
  ))
_sym_db.RegisterMessage(Heading)


# @@protoc_insertion_point(module_scope)
