# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perception_ultrasonic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='perception_ultrasonic.proto',
  package='adu.common.perception',
  syntax='proto2',
  serialized_pb=_b('\n\x1bperception_ultrasonic.proto\x12\x15\x61\x64u.common.perception\x1a\x0cheader.proto\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\x80\x01\n\x16ImpendingCollisionEdge\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63one_id_list\x18\x02 \x03(\x05\x12-\n\x05point\x18\x03 \x03(\x0b\x32\x1e.adu.common.perception.Point3D\x12\x15\n\rtracking_time\x18\x04 \x01(\x01\"\x95\x01\n\x17ImpendingCollisionEdges\x12O\n\x18impending_collision_edge\x18\x01 \x03(\x0b\x32-.adu.common.perception.ImpendingCollisionEdge\x12)\n\x06header\x18\x02 \x01(\x0b\x32\x19.adu.common.header.Header')
  ,
  dependencies=[header__pb2.DESCRIPTOR,])




_POINT3D = _descriptor.Descriptor(
  name='Point3D',
  full_name='adu.common.perception.Point3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='adu.common.perception.Point3D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='adu.common.perception.Point3D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='adu.common.perception.Point3D.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=110,
)


_IMPENDINGCOLLISIONEDGE = _descriptor.Descriptor(
  name='ImpendingCollisionEdge',
  full_name='adu.common.perception.ImpendingCollisionEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='adu.common.perception.ImpendingCollisionEdge.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cone_id_list', full_name='adu.common.perception.ImpendingCollisionEdge.cone_id_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='adu.common.perception.ImpendingCollisionEdge.point', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tracking_time', full_name='adu.common.perception.ImpendingCollisionEdge.tracking_time', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=241,
)


_IMPENDINGCOLLISIONEDGES = _descriptor.Descriptor(
  name='ImpendingCollisionEdges',
  full_name='adu.common.perception.ImpendingCollisionEdges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='impending_collision_edge', full_name='adu.common.perception.ImpendingCollisionEdges.impending_collision_edge', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.common.perception.ImpendingCollisionEdges.header', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=393,
)

_IMPENDINGCOLLISIONEDGE.fields_by_name['point'].message_type = _POINT3D
_IMPENDINGCOLLISIONEDGES.fields_by_name['impending_collision_edge'].message_type = _IMPENDINGCOLLISIONEDGE
_IMPENDINGCOLLISIONEDGES.fields_by_name['header'].message_type = header__pb2._HEADER
DESCRIPTOR.message_types_by_name['Point3D'] = _POINT3D
DESCRIPTOR.message_types_by_name['ImpendingCollisionEdge'] = _IMPENDINGCOLLISIONEDGE
DESCRIPTOR.message_types_by_name['ImpendingCollisionEdges'] = _IMPENDINGCOLLISIONEDGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point3D = _reflection.GeneratedProtocolMessageType('Point3D', (_message.Message,), dict(
  DESCRIPTOR = _POINT3D,
  __module__ = 'perception_ultrasonic_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.perception.Point3D)
  ))
_sym_db.RegisterMessage(Point3D)

ImpendingCollisionEdge = _reflection.GeneratedProtocolMessageType('ImpendingCollisionEdge', (_message.Message,), dict(
  DESCRIPTOR = _IMPENDINGCOLLISIONEDGE,
  __module__ = 'perception_ultrasonic_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.perception.ImpendingCollisionEdge)
  ))
_sym_db.RegisterMessage(ImpendingCollisionEdge)

ImpendingCollisionEdges = _reflection.GeneratedProtocolMessageType('ImpendingCollisionEdges', (_message.Message,), dict(
  DESCRIPTOR = _IMPENDINGCOLLISIONEDGES,
  __module__ = 'perception_ultrasonic_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.perception.ImpendingCollisionEdges)
  ))
_sym_db.RegisterMessage(ImpendingCollisionEdges)


# @@protoc_insertion_point(module_scope)
