# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radar_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='radar_config.proto',
  package='cybertron.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x12radar_config.proto\x12\x0f\x63ybertron.proto\"]\n\x0bRadarConfig\x12\x12\n\nextrinsics\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61n_port\x18\x02 \x01(\r\x12\x13\n\x0boutput_type\x18\x03 \x01(\r\x12\x13\n\x0bmodule_name\x18\x04 \x01(\t')
)




_RADARCONFIG = _descriptor.Descriptor(
  name='RadarConfig',
  full_name='cybertron.proto.RadarConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extrinsics', full_name='cybertron.proto.RadarConfig.extrinsics', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_port', full_name='cybertron.proto.RadarConfig.can_port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_type', full_name='cybertron.proto.RadarConfig.output_type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_name', full_name='cybertron.proto.RadarConfig.module_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['RadarConfig'] = _RADARCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadarConfig = _reflection.GeneratedProtocolMessageType('RadarConfig', (_message.Message,), dict(
  DESCRIPTOR = _RADARCONFIG,
  __module__ = 'radar_config_pb2'
  # @@protoc_insertion_point(class_scope:cybertron.proto.RadarConfig)
  ))
_sym_db.RegisterMessage(RadarConfig)


# @@protoc_insertion_point(module_scope)
