# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routing_path.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import map_geometry_pb2 as map__geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='routing_path.proto',
  package='adu.simulation',
  syntax='proto2',
  serialized_pb=_b('\n\x12routing_path.proto\x12\x0e\x61\x64u.simulation\x1a\x0cheader.proto\x1a\x12map_geometry.proto\"6\n\x0cRouteSegment\x12&\n\x05point\x18\x01 \x03(\x0b\x32\x17.adu.common.hdmap.Point\"8\n\x0eLaneChangeArea\x12&\n\x05point\x18\x01 \x03(\x0b\x32\x17.adu.common.hdmap.Point\"\xa7\x01\n\x0bRoutingPath\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.adu.common.header.Header\x12\x33\n\rroute_segment\x18\x02 \x03(\x0b\x32\x1c.adu.simulation.RouteSegment\x12\x38\n\x10lane_change_area\x18\x03 \x03(\x0b\x32\x1e.adu.simulation.LaneChangeArea')
  ,
  dependencies=[header__pb2.DESCRIPTOR,map__geometry__pb2.DESCRIPTOR,])




_ROUTESEGMENT = _descriptor.Descriptor(
  name='RouteSegment',
  full_name='adu.simulation.RouteSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='adu.simulation.RouteSegment.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=126,
)


_LANECHANGEAREA = _descriptor.Descriptor(
  name='LaneChangeArea',
  full_name='adu.simulation.LaneChangeArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='adu.simulation.LaneChangeArea.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=184,
)


_ROUTINGPATH = _descriptor.Descriptor(
  name='RoutingPath',
  full_name='adu.simulation.RoutingPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.simulation.RoutingPath.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route_segment', full_name='adu.simulation.RoutingPath.route_segment', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane_change_area', full_name='adu.simulation.RoutingPath.lane_change_area', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=354,
)

_ROUTESEGMENT.fields_by_name['point'].message_type = map__geometry__pb2._POINT
_LANECHANGEAREA.fields_by_name['point'].message_type = map__geometry__pb2._POINT
_ROUTINGPATH.fields_by_name['header'].message_type = header__pb2._HEADER
_ROUTINGPATH.fields_by_name['route_segment'].message_type = _ROUTESEGMENT
_ROUTINGPATH.fields_by_name['lane_change_area'].message_type = _LANECHANGEAREA
DESCRIPTOR.message_types_by_name['RouteSegment'] = _ROUTESEGMENT
DESCRIPTOR.message_types_by_name['LaneChangeArea'] = _LANECHANGEAREA
DESCRIPTOR.message_types_by_name['RoutingPath'] = _ROUTINGPATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RouteSegment = _reflection.GeneratedProtocolMessageType('RouteSegment', (_message.Message,), dict(
  DESCRIPTOR = _ROUTESEGMENT,
  __module__ = 'routing_path_pb2'
  # @@protoc_insertion_point(class_scope:adu.simulation.RouteSegment)
  ))
_sym_db.RegisterMessage(RouteSegment)

LaneChangeArea = _reflection.GeneratedProtocolMessageType('LaneChangeArea', (_message.Message,), dict(
  DESCRIPTOR = _LANECHANGEAREA,
  __module__ = 'routing_path_pb2'
  # @@protoc_insertion_point(class_scope:adu.simulation.LaneChangeArea)
  ))
_sym_db.RegisterMessage(LaneChangeArea)

RoutingPath = _reflection.GeneratedProtocolMessageType('RoutingPath', (_message.Message,), dict(
  DESCRIPTOR = _ROUTINGPATH,
  __module__ = 'routing_path_pb2'
  # @@protoc_insertion_point(class_scope:adu.simulation.RoutingPath)
  ))
_sym_db.RegisterMessage(RoutingPath)


# @@protoc_insertion_point(module_scope)
