# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_gnss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_geometry_pb2 as common__geometry__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_gnss.proto',
  package='adu.common.sensor',
  syntax='proto2',
  serialized_pb=_b('\n\x11sensor_gnss.proto\x12\x11\x61\x64u.common.sensor\x1a\x15\x63ommon_geometry.proto\x1a\x0cheader.proto\"\xc8\x03\n\x04Gnss\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.adu.common.header.Header\x12\x18\n\x10measurement_time\x18\x02 \x01(\x01\x12\x1b\n\x10velocity_latency\x18\x03 \x01(\x02:\x01\x30\x12&\n\x08position\x18\x04 \x01(\x0b\x32\x14.adu.common.PointLLH\x12-\n\x10position_std_dev\x18\x05 \x01(\x0b\x32\x13.adu.common.Point3D\x12,\n\x0flinear_velocity\x18\x06 \x01(\x0b\x32\x13.adu.common.Point3D\x12\x34\n\x17linear_velocity_std_dev\x18\x07 \x01(\x0b\x32\x13.adu.common.Point3D\x12\x10\n\x08num_sats\x18\x08 \x01(\x05\x12*\n\x04type\x18\t \x01(\x0e\x32\x1c.adu.common.sensor.Gnss.Type\"e\n\x04Type\x12\x0b\n\x07INVALID\x10\x00\x12\x0e\n\nPROPAGATED\x10\x01\x12\n\n\x06SINGLE\x10\x02\x12\x0b\n\x07PSRDIFF\x10\x03\x12\x07\n\x03PPP\x10\x04\x12\r\n\tRTK_FLOAT\x10\x05\x12\x0f\n\x0bRTK_INTEGER\x10\x06\"\xa7\x03\n\tRangeInfo\x12\x46\n\rconstellation\x18\x01 \x01(\x0e\x32*.adu.common.sensor.RangeInfo.Constellation:\x03GPS\x12\x0b\n\x03prn\x18\x02 \x01(\x05\x12\x19\n\x11\x63\x61rrier_frequency\x18\x03 \x01(\x07\x12\x18\n\x0bpseudorange\x18\x04 \x01(\x01:\x03nan\x12 \n\x13pseudorange_std_dev\x18\x05 \x01(\x02:\x03nan\x12\x1a\n\rcarrier_phase\x18\x06 \x01(\x01:\x03nan\x12\"\n\x15\x63\x61rrier_phase_std_dev\x18\x07 \x01(\x02:\x03nan\x12\x14\n\x07\x64oppler\x18\x08 \x01(\x02:\x03nan\x12\x1c\n\x0f\x64oppler_std_dev\x18\t \x01(\x02:\x03nan\x12\x0f\n\x03\x63no\x18\n \x01(\x05:\x02-1\x12\x15\n\tlock_time\x18\x0b \x01(\x05:\x02-1\"R\n\rConstellation\x12\x07\n\x03GPS\x10\x00\x12\x0b\n\x07GLONASS\x10\x01\x12\x08\n\x04SBAS\x10\x02\x12\x0b\n\x07GALILEO\x10\x03\x12\n\n\x06\x42\x45IDOU\x10\x04\x12\x08\n\x04QZSS\x10\x05\"~\n\tGnssRange\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.adu.common.header.Header\x12\x18\n\x10measurement_time\x18\x02 \x01(\x01\x12,\n\x06ranges\x18\x03 \x03(\x0b\x32\x1c.adu.common.sensor.RangeInfo')
  ,
  dependencies=[common__geometry__pb2.DESCRIPTOR,header__pb2.DESCRIPTOR,])



_GNSS_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='adu.common.sensor.Gnss.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROPAGATED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PSRDIFF', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PPP', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTK_FLOAT', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTK_INTEGER', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=433,
  serialized_end=534,
)
_sym_db.RegisterEnumDescriptor(_GNSS_TYPE)

_RANGEINFO_CONSTELLATION = _descriptor.EnumDescriptor(
  name='Constellation',
  full_name='adu.common.sensor.RangeInfo.Constellation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GPS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLONASS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SBAS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GALILEO', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BEIDOU', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QZSS', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=878,
  serialized_end=960,
)
_sym_db.RegisterEnumDescriptor(_RANGEINFO_CONSTELLATION)


_GNSS = _descriptor.Descriptor(
  name='Gnss',
  full_name='adu.common.sensor.Gnss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.common.sensor.Gnss.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measurement_time', full_name='adu.common.sensor.Gnss.measurement_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_latency', full_name='adu.common.sensor.Gnss.velocity_latency', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='adu.common.sensor.Gnss.position', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_std_dev', full_name='adu.common.sensor.Gnss.position_std_dev', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='adu.common.sensor.Gnss.linear_velocity', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_velocity_std_dev', full_name='adu.common.sensor.Gnss.linear_velocity_std_dev', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_sats', full_name='adu.common.sensor.Gnss.num_sats', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='adu.common.sensor.Gnss.type', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GNSS_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=534,
)


_RANGEINFO = _descriptor.Descriptor(
  name='RangeInfo',
  full_name='adu.common.sensor.RangeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='constellation', full_name='adu.common.sensor.RangeInfo.constellation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prn', full_name='adu.common.sensor.RangeInfo.prn', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_frequency', full_name='adu.common.sensor.RangeInfo.carrier_frequency', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pseudorange', full_name='adu.common.sensor.RangeInfo.pseudorange', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=(1e10000 * 0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pseudorange_std_dev', full_name='adu.common.sensor.RangeInfo.pseudorange_std_dev', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=(1e10000 * 0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_phase', full_name='adu.common.sensor.RangeInfo.carrier_phase', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=(1e10000 * 0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_phase_std_dev', full_name='adu.common.sensor.RangeInfo.carrier_phase_std_dev', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=(1e10000 * 0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doppler', full_name='adu.common.sensor.RangeInfo.doppler', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=(1e10000 * 0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doppler_std_dev', full_name='adu.common.sensor.RangeInfo.doppler_std_dev', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=(1e10000 * 0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cno', full_name='adu.common.sensor.RangeInfo.cno', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lock_time', full_name='adu.common.sensor.RangeInfo.lock_time', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RANGEINFO_CONSTELLATION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=960,
)


_GNSSRANGE = _descriptor.Descriptor(
  name='GnssRange',
  full_name='adu.common.sensor.GnssRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='adu.common.sensor.GnssRange.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measurement_time', full_name='adu.common.sensor.GnssRange.measurement_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranges', full_name='adu.common.sensor.GnssRange.ranges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=962,
  serialized_end=1088,
)

_GNSS.fields_by_name['header'].message_type = header__pb2._HEADER
_GNSS.fields_by_name['position'].message_type = common__geometry__pb2._POINTLLH
_GNSS.fields_by_name['position_std_dev'].message_type = common__geometry__pb2._POINT3D
_GNSS.fields_by_name['linear_velocity'].message_type = common__geometry__pb2._POINT3D
_GNSS.fields_by_name['linear_velocity_std_dev'].message_type = common__geometry__pb2._POINT3D
_GNSS.fields_by_name['type'].enum_type = _GNSS_TYPE
_GNSS_TYPE.containing_type = _GNSS
_RANGEINFO.fields_by_name['constellation'].enum_type = _RANGEINFO_CONSTELLATION
_RANGEINFO_CONSTELLATION.containing_type = _RANGEINFO
_GNSSRANGE.fields_by_name['header'].message_type = header__pb2._HEADER
_GNSSRANGE.fields_by_name['ranges'].message_type = _RANGEINFO
DESCRIPTOR.message_types_by_name['Gnss'] = _GNSS
DESCRIPTOR.message_types_by_name['RangeInfo'] = _RANGEINFO
DESCRIPTOR.message_types_by_name['GnssRange'] = _GNSSRANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gnss = _reflection.GeneratedProtocolMessageType('Gnss', (_message.Message,), dict(
  DESCRIPTOR = _GNSS,
  __module__ = 'sensor_gnss_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.sensor.Gnss)
  ))
_sym_db.RegisterMessage(Gnss)

RangeInfo = _reflection.GeneratedProtocolMessageType('RangeInfo', (_message.Message,), dict(
  DESCRIPTOR = _RANGEINFO,
  __module__ = 'sensor_gnss_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.sensor.RangeInfo)
  ))
_sym_db.RegisterMessage(RangeInfo)

GnssRange = _reflection.GeneratedProtocolMessageType('GnssRange', (_message.Message,), dict(
  DESCRIPTOR = _GNSSRANGE,
  __module__ = 'sensor_gnss_pb2'
  # @@protoc_insertion_point(class_scope:adu.common.sensor.GnssRange)
  ))
_sym_db.RegisterMessage(GnssRange)


# @@protoc_insertion_point(module_scope)
