# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_sim_world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import simulation_common_pb2 as simulation__common__pb2
import simulation_world_pb2 as simulation__world__pb2
import monitor_result_pb2 as monitor__result__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='update_sim_world.proto',
  package='adu.simulation',
  syntax='proto2',
  serialized_pb=_b('\n\x16update_sim_world.proto\x12\x0e\x61\x64u.simulation\x1a\x17simulation_common.proto\x1a\x16simulation_world.proto\x1a\x14monitor_result.proto\"V\n\tPushWorld\x12\x32\n\tsim_world\x18\x01 \x01(\x0b\x32\x1f.adu.simulation.SimulationWorld\x12\x15\n\rtimestamp_sec\x18\x02 \x01(\x01\x32\xb3\x01\n\x0eUpdateSimWorld\x12H\n\x0bUpdateWorld\x12\x19.adu.simulation.PushWorld\x1a\x1c.adu.simulation.UpdateStatus\"\x00\x12W\n\x11PushMonitorStatus\x12\".adu.common.monitor.MonitortResult\x1a\x1c.adu.simulation.UpdateStatus\"\x00')
  ,
  dependencies=[simulation__common__pb2.DESCRIPTOR,simulation__world__pb2.DESCRIPTOR,monitor__result__pb2.DESCRIPTOR,])




_PUSHWORLD = _descriptor.Descriptor(
  name='PushWorld',
  full_name='adu.simulation.PushWorld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sim_world', full_name='adu.simulation.PushWorld.sim_world', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_sec', full_name='adu.simulation.PushWorld.timestamp_sec', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=199,
)

_PUSHWORLD.fields_by_name['sim_world'].message_type = simulation__world__pb2._SIMULATIONWORLD
DESCRIPTOR.message_types_by_name['PushWorld'] = _PUSHWORLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushWorld = _reflection.GeneratedProtocolMessageType('PushWorld', (_message.Message,), dict(
  DESCRIPTOR = _PUSHWORLD,
  __module__ = 'update_sim_world_pb2'
  # @@protoc_insertion_point(class_scope:adu.simulation.PushWorld)
  ))
_sym_db.RegisterMessage(PushWorld)



_UPDATESIMWORLD = _descriptor.ServiceDescriptor(
  name='UpdateSimWorld',
  full_name='adu.simulation.UpdateSimWorld',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=202,
  serialized_end=381,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateWorld',
    full_name='adu.simulation.UpdateSimWorld.UpdateWorld',
    index=0,
    containing_service=None,
    input_type=_PUSHWORLD,
    output_type=simulation__common__pb2._UPDATESTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PushMonitorStatus',
    full_name='adu.simulation.UpdateSimWorld.PushMonitorStatus',
    index=1,
    containing_service=None,
    input_type=monitor__result__pb2._MONITORTRESULT,
    output_type=simulation__common__pb2._UPDATESTATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATESIMWORLD)

DESCRIPTOR.services_by_name['UpdateSimWorld'] = _UPDATESIMWORLD

# @@protoc_insertion_point(module_scope)
